// Vehicle image mapping — generated by car-image-scraper
// Re-run `npm run scrape` in car-image-scraper/ to regenerate

const CAR_IMAGES: Record<string, string> = {
  "honda-civic-silver": "/cars/honda-civic-silver.jpg",
  "ford-transit-white": "/cars/ford-transit-white.jpg",
  "toyota-camry-blue": "/cars/toyota-camry-blue.jpg",
  "hyundai-elantra-black": "/cars/hyundai-elantra-black.jpg",
  "chevrolet-express-white": "/cars/chevrolet-express-white.jpg",
  "nissan-altima-red": "/cars/nissan-altima-red.jpg",
  "mercedes-sprinter-white": "/cars/mercedes-sprinter-white.jpg",
  "subaru-outback-green": "/cars/subaru-outback-green.jpg",
  "bmw-3-series-black": "/cars/bmw-3-series-black.jpg",
  "ram-promaster-white": "/cars/ram-promaster-white.jpg",
  "ford-focus-blue": "/cars/ford-focus-blue.jpg",
  "kia-forte-silver": "/cars/kia-forte-silver.jpg",
  "honda-accord-white": "/cars/honda-accord-white.jpg",
  "mazda-3-red": "/cars/mazda-3-red.jpg",
  "volkswagen-jetta-gray": "/cars/volkswagen-jetta-gray.jpg",
  "audi-a4-black": "/cars/audi-a4-black.jpg",
  "toyota-corolla-white": "/cars/toyota-corolla-white.jpg",
  "lexus-es-silver": "/cars/lexus-es-silver.jpg",
  "honda-cr-v-blue": "/cars/honda-cr-v-blue.jpg",
  "chevrolet-malibu-black": "/cars/chevrolet-malibu-black.jpg",
  "tesla-model-3-white": "/cars/tesla-model-3-white.jpg",
  "hyundai-sonata-silver": "/cars/hyundai-sonata-silver.jpg",
  "dodge-charger-black": "/cars/dodge-charger-black.jpg",
  "toyota-rav4-silver": "/cars/toyota-rav4-silver.jpg",
  "subaru-impreza-blue": "/cars/subaru-impreza-blue.jpg"
}

export function getCarImageUrl(make: string, model: string, color: string): string {
  const key = `${make}-${model}-${color}`.toLowerCase().replace(/\s+/g, '-')
  return CAR_IMAGES[key] ?? '/cars/honda-civic-silver.jpg'
}
